In [2]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#WAP to convert 1d array to 2d array
#np.arange(start, stop, step)
# where:

# start → Starting number (default = 0)
# stop → Ending number (not included)
# step → Difference between consecutive numbers (default = 1)
arr = np.arange(6)
arr_2d = arr.reshape(2,3)
print(arr_2d)

[[0 1 2]
 [3 4 5]]


In [4]:
import numpy as np

#create the 4X2 array of type assigned int16
#we use np.array() and specify the dtype
my_array =  np.array([[1,2],[3,4],[5,6],[7,8]],dtype=np.uint16)

#print the attributes 
print("the shape of the array is ",my_array.shape)
print("the number of dimensions of the array is ",my_array.ndim)
print("the size of each element in byte is:",my_array.itemsize)


the shape of the array is  (4, 2)
the number of dimensions of the array is  2
the size of each element in byte is: 2


In [5]:
#extract the documentation of numpy's arange() function 
import numpy as np
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [6]:
#create a 1d array filled with zeros and another filled with ones 

#expected output
#Zeros:[0,0,0,0,0]
#Ones:[1,1,1,1,1]
import numpy as np
zero_arr = np.zeros(5)
ones_arr = np.ones(5)
print("zeros:",zero_arr)
print("ones:",ones_arr)

zeros: [0. 0. 0. 0. 0.]
ones: [1. 1. 1. 1. 1.]


In [7]:
#create a 1d array pf 10 evenly spaced values between 5 and 50

#expected output:
#[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
#syntax linspace(start,stop,num)
import numpy as np
arr = np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [9]:
import numpy as np
py_list = [1,2,3,4,5]
arr = np.array(py_list)
print(arr)

[1 2 3 4 5]


In [8]:
#find the memory size of a numpy array of number from 0 to 9
#expected output:
#array :[0 1 2 3 4 5 6 7 8 9]
#memory size of the array is: 40 bytes
import numpy as np
arr = np.arange(10)
print("array:",arr)
print("memory size of the array is:",arr.nbytes,"bytes")

array: [0 1 2 3 4 5 6 7 8 9]
memory size of the array is: 40 bytes


In [ ]:
#reverse a 1D numpy array 
# When Python sees a negative step, it automatically assumes:

# Start = last element

# Stop = before the first element

# Move backwards
import numpy as np
arr =np.arange(10)
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [ ]:
#create a 3x3 identity matrix 
import numpy as np
identity  = np.eye(3)#"Create an identity matrix with 3 rows and 3 columns."
print("3x3 identity matrix:\n",identity)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create a 4x4 array and extracr its first row and last column
#expected output:

#array
#[[ 1  2  3  4]
# [ 5  6  7  8]
# [ 9 10 11 12]
# [13 14 15 16]]
#first row: [1 2 3 4]
#last column: [ 4  8 12 16]
import numpy as np 
arr = np.arange(1,17).reshape(4,4)
print("array\n",arr)
first_row = arr[0]
print("first row:",first_row)
last_column = arr[:,-1]
print("last column:",last_column)

array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
first row: [1 2 3 4]
last column: [ 4  8 12 16]


In [14]:
#extract odd rows and even columns 
#problem breakdown
#rows:In programming,indexing starts at 0,Odd-indexed rows wolid be rows 1 and 3 
#Columns:Even-indexed columns would be columns 0 and 2
import numpy as np

sampleArray = np.array([[3,6,9,12],
                       [15,18,21,24],
                       [27,30,33,36],
                       [39,42,45,48],
                    [51,54,57,60]])

#use the slicing technique to extract odd rows and even columns
#the slice [1::2] selects every second element starting from index 1 (odd rows),
#the slice [::2] selects every second element starting from index 0 (even columns).

newArray = sampleArray[1::2, ::2]
print("Original array:\n", sampleArray)
print("Extracted array:\n", newArray)

Original array:
 [[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
Extracted array:
 [[15 21]
 [39 45]]
